# This workflow organizes new issues

name: New issue handler

on:
  issues:
    types: [opened]

jobs:
  # Add the [idea] label to new issues
  labelNewIssue:
    runs-on: ubuntu-latest
    steps:
    - run: >
        gh issue edit $ISSUE --repo $REPO --add-label idea
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
      
  # Comment on new issues
  commentNewIssue:
    runs-on: ubuntu-latest
    steps:
    - run: >
        gh issue comment $ISSUE --repo $REPO --body "Thank you for opening this issue! We are labeling it with [idea] so we can review it and come back to you ASAP. 
        You can ask for this issue in the comments if you want to work on it, but please don't start working until is reviewed and assigned to you."
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
      
  
